manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: biggus22
      url-base: https://github.com/Biggus22
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: Jesterpad
      remote: biggus22
      revision: main
      path: modules/Jesterpad
  self:
    path: config